# This is a basic workflow to help you get started with Actions

name: "DB Data h"

# Controls when the workflow will run
on:
  schedule:
  - cron: "30 14 * * *"
  
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Check out repo
        uses: actions/checkout@v2


      - name: test
        run: echo Hello amitp0
        
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  
          
      - name: install python packages
        run: |
          pip install --upgrade pip 
          pip install opencv-python
          pip install requests
          pip install pdf2image
          pip install Pillow
          pip install pyrebase
          pip install pytesseract
          pip install pandas
          
      - name: Install poppler
        run:  |
          sudo apt install tesseract-ocr
          sudo apt-get install poppler-utils
 
  
      - name: Job done
        run: echo Job done successfully
        
      - name: Check py file
        run: python eas.py
            
